export const originalProducts = [
  { name: "Bottled Water", stock: 33, avgSales: 24, leadTime: 1 },
  { name: "Apple", stock: 22, avgSales: 56, leadTime: 7 },
  { name: "Banana", stock: 12, avgSales: 40, leadTime: 3 },
  { name: "Orange Juice", stock: 34, avgSales: 20, leadTime: 7 },
  { name: "White Bread", stock: 18, avgSales: 28, leadTime: 4 },
  { name: "Rice (5kg)", stock: 45, avgSales: 30, leadTime: 2 },
  { name: "Cooking Oil", stock: 48, avgSales: 24, leadTime: 10 },
  { name: "Granulated Sugar", stock: 43, avgSales: 54, leadTime: 1 },
  { name: "Table Salt", stock: 18, avgSales: 12, leadTime: 3 },
  { name: "Eggs (dozen)", stock: 49, avgSales: 44, leadTime: 3 },
  { name: "Fresh Milk (1L)", stock: 15, avgSales: 53, leadTime: 8 },
  { name: "Cheddar Cheese", stock: 7, avgSales: 27, leadTime: 2 },
  { name: "Butter", stock: 20, avgSales: 24, leadTime: 10 },
  { name: "Yogurt (pack)", stock: 31, avgSales: 56, leadTime: 8 },
  { name: "Chicken Meat (kg)", stock: 3, avgSales: 17, leadTime: 2 },
  { name: "Beef Steak (kg)", stock: 6, avgSales: 7, leadTime: 5 },
  { name: "Pork Chops", stock: 25, avgSales: 33, leadTime: 5 },
  { name: "Fish Fillet", stock: 10, avgSales: 44, leadTime: 9 },
  { name: "Frozen Vegetables", stock: 23, avgSales: 10, leadTime: 5 },
  { name: "Potato (kg)", stock: 3, avgSales: 9, leadTime: 1 },
  { name: "Onion (kg)", stock: 44, avgSales: 11, leadTime: 1 },
  { name: "Garlic (pack)", stock: 21, avgSales: 31, leadTime: 5 },
  { name: "Tomato (kg)", stock: 30, avgSales: 26, leadTime: 4 },
  { name: "Cucumber", stock: 42, avgSales: 25, leadTime: 10 },
  { name: "Carrot (kg)", stock: 33, avgSales: 40, leadTime: 5 },
  { name: "Lettuce", stock: 21, avgSales: 1, leadTime: 9 },
  { name: "Spinach (pack)", stock: 14, avgSales: 35, leadTime: 7 },
  { name: "Coffee (ground)", stock: 0, avgSales: 41, leadTime: 10 },
  { name: "Tea Bags", stock: 42, avgSales: 13, leadTime: 1 },
  { name: "Soda (cans)", stock: 47, avgSales: 4, leadTime: 7 },
  { name: "Dog Food (kg)", stock: 0, avgSales: 35, leadTime: 6 },
  { name: "Cat Food (can)", stock: 27, avgSales: 15, leadTime: 3 },
  { name: "Wet Wipes", stock: 6, avgSales: 12, leadTime: 8 },
  { name: "Toilet Paper (rolls)", stock: 14, avgSales: 20, leadTime: 7 },
  { name: "Paper Towels", stock: 28, avgSales: 11, leadTime: 4 },
  { name: "Shampoo", stock: 5, avgSales: 18, leadTime: 6 },
  { name: "Conditioner", stock: 34, avgSales: 22, leadTime: 4 },
  { name: "Soap Bar", stock: 37, avgSales: 28, leadTime: 3 },
  { name: "Body Wash", stock: 12, avgSales: 16, leadTime: 5 },
  { name: "Toothpaste", stock: 44, avgSales: 9, leadTime: 4 },
  { name: "Toothbrush", stock: 25, avgSales: 7, leadTime: 6 },
  { name: "Laundry Detergent", stock: 39, avgSales: 9, leadTime: 10 },
  { name: "Fabric Softener", stock: 22, avgSales: 14, leadTime: 6 },
  { name: "Dish Soap", stock: 17, avgSales: 19, leadTime: 5 },
  { name: "Sponge", stock: 11, avgSales: 8, leadTime: 3 },
  { name: "Trash Bags", stock: 7, avgSales: 12, leadTime: 6 },
  { name: "Aluminum Foil", stock: 30, avgSales: 5, leadTime: 4 },
  { name: "Plastic Wrap", stock: 9, avgSales: 6, leadTime: 7 },
  { name: "Food Storage Bags", stock: 18, avgSales: 10, leadTime: 3 },
  { name: "Light Bulb (pack)", stock: 26, avgSales: 2, leadTime: 8 },
  { name: "Batteries AA", stock: 20, avgSales: 9, leadTime: 5 },
  { name: "Batteries AAA", stock: 8, avgSales: 6, leadTime: 7 },
  { name: "Phone Charger", stock: 16, avgSales: 3, leadTime: 6 },
  { name: "Power Bank", stock: 4, avgSales: 2, leadTime: 10 },
  { name: "Rice Cooker", stock: 12, avgSales: 1, leadTime: 9 },
  { name: "Microwave Oven", stock: 2, avgSales: 1, leadTime: 14 },
  { name: "Toaster", stock: 9, avgSales: 2, leadTime: 12 },
  { name: "Electric Kettle", stock: 31, avgSales: 8, leadTime: 6 },
  { name: "Blender", stock: 6, avgSales: 5, leadTime: 9 },
  { name: "Air Fryer", stock: 3, avgSales: 3, leadTime: 14 },
  { name: "Frying Pan", stock: 19, avgSales: 11, leadTime: 6 },
  { name: "Saucepan", stock: 21, avgSales: 9, leadTime: 5 },
  { name: "Knife Set", stock: 29, avgSales: 2, leadTime: 7 },
  { name: "Cutting Board", stock: 23, avgSales: 4, leadTime: 3 },
  { name: "Plates Set", stock: 38, avgSales: 1, leadTime: 12 },
  { name: "Glasses Set", stock: 27, avgSales: 2, leadTime: 8 },
  { name: "Mugs (set)", stock: 41, avgSales: 2, leadTime: 6 },
  { name: "Dining Table", stock: 1, avgSales: 0, leadTime: 30 },
  { name: "Chair", stock: 5, avgSales: 1, leadTime: 20 },
  { name: "Bed Sheet Set", stock: 7, avgSales: 2, leadTime: 10 },
  { name: "Pillow", stock: 10, avgSales: 3, leadTime: 7 },
  { name: "Blanket", stock: 11, avgSales: 1, leadTime: 12 },
  { name: "Towels (pack)", stock: 15, avgSales: 5, leadTime: 8 },
  { name: "First Aid Kit", stock: 6, avgSales: 1, leadTime: 14 },
  { name: "Bandages", stock: 24, avgSales: 4, leadTime: 4 },
  { name: "Pain Reliever (pack)", stock: 28, avgSales: 10, leadTime: 6 },
  { name: "Hand Sanitizer", stock: 13, avgSales: 9, leadTime: 5 },
  { name: "Face Mask (box)", stock: 32, avgSales: 6, leadTime: 4 },
  { name: "Vaseline", stock: 17, avgSales: 3, leadTime: 8 },
  { name: "Sunscreen", stock: 9, avgSales: 2, leadTime: 11 },
  { name: "Lip Balm", stock: 39, avgSales: 7, leadTime: 5 },
  { name: "Perfume (bottle)", stock: 2, avgSales: 1, leadTime: 20 },
  { name: "Deodorant", stock: 35, avgSales: 6, leadTime: 6 },
  { name: "Razor", stock: 26, avgSales: 5, leadTime: 9 },
  { name: "Shaving Cream", stock: 18, avgSales: 4, leadTime: 6 },
  { name: "Makeup Remover", stock: 14, avgSales: 3, leadTime: 7 },
  { name: "Hand Mixer", stock: 3, avgSales: 0, leadTime: 12 },
  { name: "Desk Lamp", stock: 8, avgSales: 1, leadTime: 10 },
  { name: "Electric Fan", stock: 20, avgSales: 4, leadTime: 9 },
  { name: "Heater (portable)", stock: 2, avgSales: 0, leadTime: 30 },
  { name: "bola", stock: 12, avgSales: 2, leadTime: 7 },
  { name: "Backpack", stock: 11, avgSales: 3, leadTime: 8 },
  { name: "Wallet", stock: 16, avgSales: 1, leadTime: 12 },
  { name: "Socks (pack)", stock: 22, avgSales: 6, leadTime: 4 },
  { name: "T-Shirt", stock: 27, avgSales: 5, leadTime: 7 },
  { name: "Jeans", stock: 5, avgSales: 1, leadTime: 20 },
  { name: "Shoes", stock: 4, avgSales: 1, leadTime: 18 },
  { name: "Watch", stock: 1, avgSales: 0, leadTime: 25 },
  { name: "hat", stock: 4, avgSales: 1, leadTime: 18 },
  { name: "brief", stock: 1, avgSales: 0, leadTime: 25 }
];
